# fly.toml app configuration file generated for taxonomy-time-machine on 2024-11-18T16:26:50-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taxonomy-time-machine'
primary_region = 'sjc'

console_command = "service nginx start && python /app/backend/app.py"

[mounts]
  source = "data"
  destination = "/data"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
